### ISSUE TITLE
restart firefox and no normal calc page

### ISSUE THREAD

**Issue by hopalongrock** [vaeth/calc-extension#4] opened 2018-02-22 12:02 UTC
If I restart firefox and the calc tab was/is active, it will be empty after restart. There is no 1+2 icon and the calc-extension title and help text is missing.

This happens rarely, accidentally, I can't reproduce it intentionally.
Maybe this is is a firefox problem.

The urlbar:

Extension (calc-extension)   moz-extension://ab6982fa-aeff-4b54-a99e-fe38d106e36a/data/tab/index.html

![image](https://user-images.githubusercontent.com/6840865/36536998-2328564c-17cf-11e8-882c-cb771ee8977d.png)

**Comment by hopalongrock** [comment] 2018-02-22 20:20
OK, I found - this occurs if the temporary add-on is loaded and is started in a tab, when I close Firefox and restart. I successfully reproduced this, using 58.0.2 .
In this case there is a contradiction between the installed and temporary add-on in the tab.

**Comment by vaeth** [comment] 2018-02-22 21:24
In this case I would close this as "not a bug": Incompatibilities when mixing the background script of an older version (after the restart) with the code running inside of the tab of the new version are to be expected. The way how these parts of the extension communicate with each other has changed and will likely also change in the future.

**Comment by hopalongrock** [comment] 2018-02-23 07:22
OK

**Closed as completed** 2018-02-25 07:19 UTC
