### ISSUE TITLE
Saving the content

### ISSUE THREAD

**Issue by hopalongrock** [vaeth/calc-extension#3] opened 2018-02-22 09:02 UTC
I asked you already about saving, etc

I found different "Sticky Notes", sticky calculator add-ons, they show the content after restart, so possibly you could do the same.
For example Sticky Notes by Trishul 
"This extension puts a button in your toolbar, which when clicked open a popup with a text field.
You can write anything there, that will be retained till you clear the text manually.
Even after closing browser and reopening its retained.
This will be available in toolbar irrespective of the page you are."

**Comment by vaeth** [comment] 2018-02-22 14:48
The extension already requires the storage permission to save the option settings in local storage (in contrast to sync storage which is synced across platforms).
Technically, it is not a problem to store also a session locally.

The problem is the user interface: In contrast to the sticky notes you mentioned, it is intentional that you can have several independent calc-extension windows open simultaneously.

There are many ways how it can be realized. As already mentioned, it starts with the decision
1. whether to store locally or syncing across devices. Next decision is
2. whether to store only one session or give somehow a possibility to store several sessions. Further:
3. when restoring, should the data be added to the current session or should it replace the current session (or even let the user choose between both).

In the moment, I think it would make most sense to add one button for store and one for "adding" a session to the current one, and that only one session is stored (i.e. storing a further session will remove the previously stored one), and to store the session only locally.

**Comment by hopalongrock** [comment] 2018-02-22 18:28
For bigger tasks, when to keep the data is important, I rather use local Windows-based programs/solutions, with extra safeguards.
For me working with a browser calculator was always a short-term solution, so to save only one session is enough.

**Comment by vaeth** [comment] 2018-02-24 19:49
The current master branch is now ready for testing for the next release.

It contains buttons to store a session and to add it to the current session.
In addition, there is a button to copy a whole session to the clipboard.
There are other minor usability improvements like a button for clearing or the possibility to remove a line when it has empty output.
The most cumbersome change was the adding of input mode, size, and output base to the options (which are stored) and to the head of the calculation sheet.

Note that all these things interact. In particular, if you change a value on the options page, it will change all corresponding values in the open sessions. Similarly, if you clear the storage, no open session will be able to load it anymore and thus has to disable the corresponding button. Of course, you can also store a session in one window and then add it to another (already open) window.

**Comment by hopalongrock** [comment] 2018-02-25 07:54
Very clear and understandable except:
-In options and session pages please use the "Tab" and "Enter" text to, not only the graphical symbols.
-In Options modifier !/? (↪ off/on) : the three symbol one after another too compact for me

Please make the automatic copy of result to clipboard optional, or leave it, maybe the explicit copy is enough.
Setting the base to 8 on options page doesn't result octal numbers
![image](https://user-images.githubusercontent.com/6840865/36639178-48cdf746-1a07-11e8-90a6-4a03ee595f2d.png)

![image](https://user-images.githubusercontent.com/6840865/36639188-825a3826-1a07-11e8-93ab-6ab178ea7a41.png)

As you can see, the result isn't in octal. If I change the base to 10 in the session, calculate, change back to 8, then the result of 1+7 is 10 (in base 8)

Copy to clipboard works fine, however the ? before the result for me is funny, maybe the = would be better.
I Store session, but add stored session in a new session doesn't work.
Clear window works, but then Add stored session doesn't work.

**Comment by vaeth** [comment] 2018-02-25 08:59
> -In options and session pages please use the "Tab" and "Enter" text to, not only the graphical symbols.

Done for "Enter". What do you mean my "Tab"? The ↪ button really only has this symbol on it. In the options page and in the popup window there is more space for explanation, but the description of the checkbox in the main window is already too long, so I need to save space.

> -In Options modifier !/? (↪ off/on) : the three symbol one after another too compact for me

Reformulated; I think the space is affordable here.

> Please make the automatic copy of result to clipboard optional

This requires a new option; will need time to implement.

> Setting the base to 8 on options page doesn't result octal numbers

I cannot reproduce this: When I set 8 in the options page (and press e.g. enter), the result of the next calculation on the main window is displayed in octal.
Maybe there is a misunderstanding: The displayed value only refers to the result of the next calculation; already printed results are never modified.
In particular, you can have sessions with varying bases in the output (that's why the basis is explicitly mentioned after every result - unless in the decimal case when the 0/empty value is used).

If you see a ? before the result you have an encoding problem in the application into which you paste:
This is actually the ↪ symbol (utf-8).
I have chosen this symbol, because it is also on the button (and in the text when the button is omitted).
The = symbol is misleading, because you can have an expression like
```
(a
=1)+2
```
(if you use the default textfield where you can have newlines.)
I would also have preferred an ASCII symbol, but all of them are misleading or very strange.

> Store session, but add stored session in a new session doesn't work

This bug should now be fixed in the master branch.
(I didn't realize it, because the bug did not occur when you reloaded the extension after storing which I always did to simulate a browser restart.)

**Comment by vaeth** [comment] 2018-02-25 12:03
>>  Please make the automatic copy of result to clipboard optional
> This requires a new option; will need time to implement.

This is now implemented in the master branch.

**Comment by hopalongrock** [comment] 2018-02-25 12:04
Unfortunately I (and probably other people) don't have symbols on the keyboard:  neither ↪ symbol (calculate) nor enter symbol: the enter key has only "Enter", the tab key has "Tab" and the symbol ![image](https://user-images.githubusercontent.com/6840865/36640979-d85a80fc-1a28-11e8-8c72-d524b969bde3.png)

From the text  
> New lines without ↪ button

 I think this is the Tab key.

> I cannot reproduce this: When I set 8 in the options page (and press e.g. enter), the result of the next calculation on the main window is displayed in octal.

Funny, you can even see from the session image, that the base is 8 (I didn't modified the base after the expressions).

![image](https://user-images.githubusercontent.com/6840865/36640667-c1f63a04-1a23-11e8-83a2-69ecdb2381eb.png)

> If you see a ? before the result you have an encoding problem in the application into which you paste:

That's true, I didn't know about this utf-8 symbol, and my applications doesn't show it, only Word.

> 
> This is actually the ↪ symbol (utf-8).
> I have chosen this symbol, because it is also on the button (and in the text when the button is omitted).
> The = symbol is misleading, because you can have an expression 

Maybe you could use < or > or @ or [ or other spec character, not used in expressions or in a variable names.

Store, clear window, add stored session works partly, see example in previous message.:
![image](https://user-images.githubusercontent.com/6840865/36641067-611ca644-1a2a-11e8-8cda-0e13328952ab.png)
There is no difference that the session is deleted or new.

**Comment by hopalongrock** [comment] 2018-02-25 13:19
The copy of result to clipboard is optional, and works fine.

Add stored session works too, but there is an extra empty expression line at 1st:
![image](https://user-images.githubusercontent.com/6840865/36641841-c1fab9fe-1a36-11e8-8392-a6b43fe265a4.png)

**Comment by vaeth** [comment] 2018-02-25 13:44
Thanks for the testing. All should be fixed now:

1. The filling of the input fields when adding the session had failed in non-button mode. (Obviously, I had tested only in the other mode).
2. Finally, I could reproduce (and fix) the issue with the ignoring of "8": It had failed when a new window was opened after setting it in the options. (When the window was already open, the changing had worked.)
3. Instead of the utf8-symbol ↪ (for me, it is a hookrightarrow), I use now throughout ~>. This is not so nice but has no encoding issues and also cannot occur in expressions (even if someday the “language” for the expressions should be extended, I cannot imagine that this sign combination would ever get a proper meaning). I even keep it on the button for clarity, although there is looks really like 80's code...

**Comment by vaeth** [comment] 2018-02-25 13:53
No, there is no extra line: The line was there already when you pressed the button to add the session…
You could even already have started to enter an expression in that line before pressing the button.
I had thought about removing that empty line if there was no editing in it so far, but such strange case distinctions can also lead to user surprises (e.g. which line should be the current input line after adding the session in such a case?)
I think it is better to let the user decide: If he does not want that line, he can just press enter (or the ~> button, respectively).

**Comment by hopalongrock** [comment] 2018-02-25 14:22
The new ~> looks fine in screen and in the saved text file.

> ... If he does not want that line, he can just press enter (or the ~> button, respectively).

Maybe after the _Clear window_ button you could inform about this possibility, even better implement a _clear line_ button, because it may be useful to delete non-empty lines too.

**Comment by vaeth** [comment] 2018-02-25 15:47
Thank you for all the testing.

v2.0 is now released (and has even already been approved by mozilla).

> Maybe after the _Clear window_ button you could inform about this possibility

I am doing this now.
A _clear line_ button is not really possible, because to work properly, it would have to be in every line.
Of course, there might also be "insert new line", "move line up" and "move line down" buttons.
But I think this would all be more confusing than really helpful.
After all, this is not a spreadsheet, and most users will just use the extension to do some simple calculations.

**Comment by hopalongrock** [comment] 2018-02-25 17:55
I thought to remove the **current line**, but it's really easy to empty it by deleting its content and remove it by pressing Enter on the empty line.

**Closed as completed** 2018-02-25 17:55 UTC

**Comment by hopalongrock** [comment] 2018-02-25 17:59
Just a test, to see the result.

**Comment by hopalongrock** [comment] 2018-02-25 18:04
another test reply to "reply to" email address.
