### ISSUE TITLE
Problems with the Enter (no '=' button) method

### ISSUE THREAD

**Issue by hopalongrock** [vaeth/calc-extension#2] opened 2018-02-20 11:58 UTC
If I go back to an input field with Shift Tab or jump to a field with the the mouse, and press Enter, the value is calculated, but the cursor remains in this field. Leaving the field with Tab or the mouse works.

In the options text appears " if the expression was not modified, the value of '#' will not be updated".
Here, you mean the expression itself or its value.
For example I modify the expression from 12 to 12+0

An example with bad result:
expression1: 12
result1:12
expression2: #
result2: 12
go back to expression1
expression1: 122
result1: 122
expression2: #
result2:12
however expression2: #+1 gives the correct result2: 123

There are too many pitfalls, if you can't help somehow, I think I'd rather use the '=' button method.

**Comment by vaeth** [comment] 2018-02-20 16:49
> but the cursor remains in this field

This is probably a bug. I will check this later (perhaps in a few days) when I have more time.

> "if the expression was not modified, the value of '#' will not be updated"

This should probably better be  "if the expression was not modified, pressing 'enter' has no effect. In particular, the expression is not recalculated, the value of '#' will not be updated, and the next input field will not become active".
(Of course, the last part makes no sense in the moment due to the bug you mentioned first...)

Perhaps it is possible to avoid this whole problem by choosing another event. I will also check this later when I have more time.

**Comment by hopalongrock** [comment] 2018-02-20 20:15
If I restart firefox and the calc tab was/is active, it will be empty after restart, I have to reload. I don't know why, after some tries this now works fine.

**Comment by vaeth** [comment] 2018-02-21 07:36
The issues (option text and activation of next input field) have been fixed in the current master branch.
I wait probably with the next release since I have some ideas which I want to implement, still.

> If I restart firefox

Please open a new issue for every different topic.
I cannot reproduce this: In my case, the calc-extension tabs vanish when I restart firefox (which IMHO is how it should be: in the way, it is currently implemented, a session cannot survive a restart).

**Comment by hopalongrock** [comment] 2018-02-21 14:51
The new master branch basically works fine and specifically go back to previous field and Enter works too.
I do not know if it is intentional, but if that expression does not change, for Enter it will not go to the next input field.
For example it's enough to change the expression 12 to 12+0, and Enter works.

**Comment by vaeth** [comment] 2018-02-21 16:04
That's what I meant by “if the expression was not modified, pressing 'enter' has no effect.”
It suffices even that you just add a space.

The technical reason is that the "action" (calculation and jumping to the next input) is bound on the "onchanged" event which is the only reasonable event I know which I can bind for an input or textarea field.

**Comment by hopalongrock** [comment] 2018-02-21 17:56
OK, I understand.
And the extension does not receive or can not receive any notice that Enter is depressed, and for this can't change the expression with that space?
Or when the control goes back to a field, the extension can not change the expression with that space, triggering the change? In a database management program this was a standard solution in an on new field instance event handling trigger.
So it works in a simple case, only this and # issue remains.
I was created as a test for the "=" button variant a little Autohotkey script, to issue a Tab and an Enter, when Enter is pressed, It works for now, as I see it.

**Comment by vaeth** [comment] 2018-02-21 20:14
There are a lot of events one can bind to (keypress, focusin, focusout, submit, ...). As mentioned, I have to check which one might be used and how. Currently, I am too busy with real life.

Only one thing was clear to me when I did some research with it to get the enter key work for textarea: the keypress event is bad, since there are some platforms (e.g. in Asian countries) which have special utf8 input methods which in certain cases require an enter key, so that the event might be triggered when the key actually has a different “meaning”.

**Comment by vaeth** [comment] 2018-02-22 07:46
It seems that I found a way without modifying user input:

If the input element is placed inside a form element, the enter key will invoke a "submit" event. I have to cancel the actual submission and prevent autocompletion to avoid undesired side effects of the form, but then it seems to do the trick.

The current master branch contains this hack...

**Comment by hopalongrock** [comment] 2018-02-22 08:48
It's great, the new master works fine.
I tried many cases, and as I see now that # works fine too.

**Closed as completed** 2018-02-25 07:19 UTC
